### PR TITLE
Refactor polymorpic attach

### PR DESCRIPTION
**Pull request by pkboom**
This PR makes it look a bit cleaner to use attach method of polymorphic many to many. It might apply to CanBlock.php and CanLike.php, too.

### CODE REVIEW

**Comment by rennokki** [comment]
At the point I wrote the code, I had serious trust issues with `morphToMany` and using the right fields. Can you provide code change also for the rest of the traits?

**Comment by pkboom** [comment]
Will do. I will close this and submit another PR after applying this to other files. Thanks.

**Comment by rennokki** [comment]
You should have just kept the same branch and push code to it and it would reflect the changes here.

**Comment by pkboom** [comment]
Oh, got it. pretty much beginner here. Thanks for the advice.

**Pull request closed without merging**
