### PR TITLE
added support for L7

### PR DESCRIPTION
**Pull request by joveice**
Added support for L7 and updated needed packages.

### CODE REVIEW

**Comment by joveice** [comment]
@rennokki are we trying to update this package at the same time? :tada:

**Comment by rennokki** [comment]
@joveice Actually, it is already a tagged release for 7.x support 🎉

**Comment by joveice** [comment]
@rennokki But are you able to install it? I can't without adding these https://github.com/rennokki/befriended/pull/62/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R36-R37 else it only installs L6

**Comment by rennokki** [comment]
@joveice sync your branch with this repo's master and I'll take care of it :yum:

**Comment by joveice** [comment]
@rennokki There, it should be synced now

**Comment by rennokki** [comment]
Tagged that: https://github.com/rennokki/befriended/releases/tag/3.1.1

**Pull request merged**
